apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatassessment-deployment
  labels:
    app: beatassessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beatassessment
  template:
    metadata:
      labels:
        app: beatassessment
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - name: beatassessment
        image: nikosleventis/beatassessment:v0.6
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: beat-service
spec:
  type: NodePort
  selector:
    app: beatassessment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
