apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatassessment-deployment
  labels:
    app: beatassessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beatassessment
  template:
    metadata:
      labels:
        app: beatassessment
    spec:
      containers:
      - name: beatassessment
        image: nikosleventis/beatassessment:v0.6
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: beat-service
spec:
  type: NodePort
  selector:
    app: beatassessment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
